# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0002_auto_20170531_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogging.Section'),
        ),
    ]
