site_name: Blogging App
pages:
- [index.md, Home]
- [templates.md, Templates and Views]
- [plugins.md, Django-CMS plugins]
- [apis.md, Apis and Template tags]
- [demo.md, Demo Application]
theme: readthedocs
