"""
Django settings for demo project.

Generated by 'django-admin startproject' using Django 1.11.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
#Project Path is the outer demo folder. That is 2 folders back.
PROJECT_PATH = os.path.abspath(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'aqq!2(9u7w&cg3+69&on3^6+hkba+(xu9^wf0ldbdm82u*fmk#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #Bare Minimum
    'blogging',
    'taggit',
#    'ckeditor',
#    'ckeditor_uploader',
#    'mptt',
#    'rest_framework',
    #Others
    #'reversion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
        		  os.path.join(PROJECT_PATH, "templates"),
        		],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
            ],
            
            'debug': DEBUG
        },
    },
]

WSGI_APPLICATION = 'demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(PROJECT_PATH, "media")
MEDIA_URL = '/media/'

MPTT_ADMIN_LEVEL_INDENT = 20
  
REST_FRAMEWORK = {
    # Use hyperlinked styles by default.
    # Only used if the `serializer_class` attribute is not set on a view.
    'DEFAULT_MODEL_SERIALIZER_CLASS':
        'rest_framework.serializers.HyperlinkedModelSerializer',

    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}


CKEDITOR_UPLOAD_PATH="uploads/"
CKEDITOR_RESTRICT_BY_USER=True

CKEDITOR_CONFIGS = {
    'default': {                        
        'toolbar': [
                      ["Format", "Bold", "Italic", "Underline", "Strike", "Blockquote","Subscript", "Superscript", "SpellChecker"],
                      [ "Indent", "Outdent", 'JustifyLeft', 'JustifyCenter',
                 'JustifyRight', 'JustifyBlock'],
                      ["Image", "Table", "Link", "Unlink", "Anchor", "SectionLink",'NumberedList', 'BulletedList', 'HorizontalRule', 'CreateDiv'], 
                      ['Undo', 'Redo'], ["Source", 'RemoveFormat','Iframe'],["Maximize"],['ShowBlocks', 'Syntaxhighlight', 'Mathjax'],
                     ],
        'contentsCss': STATIC_URL+'css/bootstrap.css',
    
        'codemirror' : {
                        'theme': 'default',
                        'lineNumbers': 'true',
                        'lineWrapping': 'true',
                        'matchBrackets': 'true',
                        'autoCloseTags': 'false',
                        'autoCloseBrackets': 'false',
                        'enableSearchTools': 'true',
                        'enableCodeFolding': 'true',
                        'enableCodeFormatting': 'false',
                        'autoFormatOnStart': 'false',
                        'autoFormatOnModeChange': 'false',
                        'autoFormatOnUncomment': 'false',
                        'mode': 'htmlmixed',
                        'showSearchButton': 'true',
                        'showTrailingSpace': 'true',
                        'highlightMatches': 'true',
                        'showFormatButton': 'true',
                        'showCommentButton': 'true',
                        'showUncommentButton': 'true',
                        'showAutoCompleteButton': 'true',
                        'styleActiveLine': 'true'
                        },
             
             'disallowedContent':{      
                        'p h1 h2 h3 h4 span blockquote':{
                                    #Disallow setting font-family or font-size
                                    'styles':['font*'],
                                },
                        },   

                
            'allowedContent':{
                        '*': {
                              
                              'attributes': ['id', 'itemprop', 'title', 'placeholder', 'type', 'data-*'],
                              'classes':['text-center', 'text-left', 'text-right', 'text-justify', 'center-text', 'text-muted', 
                                         'align-center', 'pull-left', 'pull-right', 'center-block', 'media', 'image',
                                         'list-unstyled', 'list-inline',
                                         'language-*', '*', 
                                        ],
                            },
                        'p': {
                                'attributes': ['id'],   
                            },
                        'h1 h2 h3 h4 em i b strong caption h5 h6 u s br hr': 'true',
                        'a': {
                                'attributes': ['!href','target','name', 'id', 'name', 'rel'],
                            },      
                        'img':{
                               #Do not allow image height and width styles
                               'attributes': ['!src', 'alt', 'id'],
                            },                        
                        'span ul ol li sup sub': 'true',
                        'div':{
                               'classes':'*',
                            },
                        'iframe':{
                                'classes':'*',
                                'attributes':'*',
                            },
                        'small abbr address footer section article dl dt dd kbd var samp form label input button textarea fieldset':'true',
                        'pre':{
                               'attributes': ['title'],
                               'classes':['*']
                            },
                        'code': 'true',
                        
                        'blockquote':'true',
                        'table':'true',
                        'tr':'true',
                        'th':'true',
                        'td':'true',
                        },
            'justifyClasses': ['text-left', 'text-center', 'text-right', 'text-justify'],
            'extraPlugins': 'button,toolbar,codesnippet,about,stylescombo,richcombo,floatpanel,panel,button,listblock,dialog,dialogui,syntaxhighlight,htmlwriter,removeformat,horizontalrule,widget,lineutils,mathjax,div,fakeobjects,iframe,image2,justify,blockquote,indent,indentlist,indentblock',
            'ignoreEmptyParagraph': 'true',   
            'coreStyles_bold': {
                            'element': 'b',
                            'overrides': 'strong',
                        },
            'coreStyles_italic':{
                            'element':'i',
                            'overrides':'em',
                        },
            #'fillEmptyBlocks':'false',#Might need a callback fn
            'image2_alignClasses':['pull-left','text-center','pull-right'],
            'mathJaxClass':'math-tex',
            'mathJaxLib':STATIC_URL+'js/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML',
            'tabSpaces':'4',
            'indentClasses': ['col-xs-offset-1', 'col-xs-offset-2', 'col-xs-offset-3', 'col-xs-offset-4'],     
    },
}

MATHJAX_ENABLED=True
MATHJAX_LOCAL_PATH = 'js/MathJax/'
MATHJAX_CONFIG_FILE = "TeX-AMS-MML_HTMLorMML"
MATHJAX_CONFIG_DATA = {
    "tex2jax": {
      "inlineMath":
        [
            ['$','$'],
            ['\\(','\\)']
        ],
       "displayMath": [ ['$$','$$'], ["\\[","\\]"] ],
       "processEscapes": True
    },
    "TeX": {
       "equationNumbers": {"autoNumber": "AMS"},
    }
  }

